import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const test = process.argv[2] === "test";

// In dev/test mode, output directly into the vault plugin folder so hot-reload
// picks up every rebuild automatically without a separate install step.
import fs from "fs";
import manifest from "./manifest.json" with { type: "json" };
let mainPath = "main.js";
if (!prod) {
	const vaultPathFile = ".vault-path";
	if (fs.existsSync(vaultPathFile)) {
		const vaultPath = fs.readFileSync(vaultPathFile, "utf8").trim();
		if (vaultPath) {
			mainPath = `${vaultPath}/.obsidian/plugins/${manifest.id}/main.js`;
		}
	}
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		// Exclude punycode from externals so esbuild bundles the npm package.
		// Node.js v22+ removed it from core; Electron's renderer no longer ships it.
		...builtins.filter((m) => m !== "punycode"),
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: mainPath,
});

if (prod || test) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
